// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Couple
{
    public string Id { get; set; }

    public string Male { get; set; }

    public string Female { get; set; }

    public string Mbti { get; set; }

    public string Disc { get; set; }

    public string LoveLanguage { get; set; }

    public string BigFive { get; set; }

    public string Mbti1 { get; set; }

    public string Disc1 { get; set; }

    public string LoveLanguage1 { get; set; }

    public string BigFive1 { get; set; }

    public string MbtiResult { get; set; }

    public string DiscResult { get; set; }

    public string LoveLanguageResult { get; set; }

    public string BigFiveResult { get; set; }

    public bool? IsVirtual { get; set; }

    public string VirtualName { get; set; }

    public DateTime? VirtualDob { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Rec1 { get; set; }

    public string Rec2 { get; set; }

    public int? CreateGender { get; set; }

    public int? Status { get; set; }

    public virtual Member FemaleNavigation { get; set; }

    public virtual Member MaleNavigation { get; set; }
}