// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class ResultHistory
{
    public string Id { get; set; }

    public string MemberId { get; set; }

    public string Type { get; set; }

    public string Result { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }

    public virtual Member Member { get; set; }
}