name: PPC CI and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: PPCbackend
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "PCMS_GSU25SE26_BE/PCMS_GSU25SE26_BE.sln"
  API_PROJECT_PATH: "PCMS_GSU25SE26_BE/PPC.Controller"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION}}

      - name: Restore Packages
        run: dotnet restore ${{ env.SOLUTION_PATH}}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH}} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH}} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH}} --configuration Release --no-restore --no-build --property:PublishDir=publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: publish

  deploy:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: artifact

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: artifact
